### ISSUE TITLE
Remove spaces in the section id

### ISSUE THREAD

**Issue by gromain** [danielkvist/hugo-piercer-theme#3]
Hello,

I'm using your theme as a basis for my website, and I realized there is a little bug in the section partials.

Ideally, the html id [must not contain any whitespace](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id). However in your treatment of the title in this [line](https://github.com/danielkvist/hugo-piercer-theme/blob/master/layouts/partials/sections.html#L21), the title is not sanitized and spaces could find their way in the id.

A simple fix would be to replace `id="{{ .Title }}"` by `id="{{ .Title | anchorize }}"`.

I can create a pull request if you want.

Also, thanks for your work on this!

**Comment by dnlzrgz** [comment]
Hi!

Thank you so much for the report. Right now I don't have time to get into it, so if you want to open a PR I'll be happy to merge it later.

**Comment by gromain** [comment]
Done!

:-D
